blackmagic-debug/black-magic-org

index.md

GDBs target command is called "extended-remote" and not "extended_remote" or "extended remote"

Fixing wrong spelling of gdb extended-remote target command

---

index.md
usage/rtt.md

This adds a page under `Usage` with documentation on how to use RTT with the BMP. The contents of that are largely lifted from the `UsingRTT.md` file in the firmware repository, with some minor changes for consistency and clarity.
As there are already pages in that section for using BMP with SWO and Semihosting, this seemed to be a reasonable addition to that. It also helps make sure that the user-facing documentation is all in one place, rather than scattered between the website and the firmware repository.

Add RTT documentation to the website

---

usage/gdb-commands.md

The trailing slash resulted in a 404

Fix link to GDB manual

---

.github/workflows/website.yml

The gh-pages-build run [misc: spelling corrections #30](
https://github.com/blackmagic-debug/black-magic-org/actions/runs/4180757473) shows the following warning:
> [build gh-pages](https://github.com/blackmagic-debug/black-magic-org/actions/runs/4180757473/jobs/7242045299)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-python@v2, actions/checkout@v2, crazy-max/ghaction-github-pages@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
This pull request updates the the following actions from v2 to v3, to use node16 instead of node12:
- actions/setup-python
- actions/checkout
- crazy-max/ghaction-github-pages

Fix warning: update actions from v2 to v3, to use node16 instead of node12

---

conf.py

The gh-pages-build run [Fix link to GDB manual #31](https://github.com/blackmagic-debug/black-magic-org/actions/runs/4587408990/jobs/8100891082) failed with:
```
Extension error:
Could not import extension sphinx-favicon (exception: No module named 'sphinx-favicon')
```
According to https://pypi.org/project/sphinx-favicon/
> Between v0.2 and v1.0, the module name of the extension changed to better conform with Python standards. Please update the name used in the extension list of your conf.py from sphinx-favicon to sphinx_favicon!
The Setup Sphinx part step of the build shows that sphinx-favicon-1.0.1 is used.
This pull request therefore updates the `sphinx-favicon` to `sphinx_favicon`

Fix: update sphinx-favicon to sphinx_favicon

---

conf.py

The ablog template is warning that using recenposts.html and archives.html directly without the ablog prefix is depricated. This patch fixes this.

sphinx: This adds the missing ablog prefixes.

---

README.md
run_livereload.py

* Add the note about what packages are needed on MacOS.
* Add `make html` at the beginning of run_livereload script to make sure we have content to serve.
* Add console output explaining how to stop livereload.
Closes #17

livereload: Small usability improvements and documentation.

---

hardware.md
index.md

update Black Pill v2 to Black Pill F4, to make the website consistent with the changes done in https://github.com/blackmagic-debug/blackmagic/pull/1491.
- update index page
- update Black Pill v2 to Black Pill F4, and add links to respective platforms: blackpill-f401cc, blackpill-f401ce, blackpill-f411ce
- fix typo in ST-Link v3
- update hardware page
- add section on Black Pill F4 for the Black Pill boards with F401CC, F401CE, F411CE microcontrollers

Feature: update Black Pill v2 to Black Pill F4

---

usage/gdb-commands.md

Update the example `monitor help` output after the changes from blackmagic-debug/blackmagic#1474 and mention that the commands only support plain integers, not units.

blackmagic#1474 follow-up: Update help, mention units are not supported

---

upgrade.md

In PR #20 the documentation for stlink-tool was overhauled and we had an outstanding TODO in needing to build a version of the tool's repository that had all the fixes from Uwe and us merged into the default branch to make using it easier. We finally got around to dealing with this, so this PR addresses the documentation on the website which is now outdated.
We have adjusted the documentation and link for stlink-tool now that we have a dealt with the repo side of things.

Fix: ST-Link upgrade documentation

---

index.md
knowledge/faq.md
supported-targets.md

This PR defines a table of all the supported targets, what files implement the support, and what version of the firmware the support was introduced. This complements the index page supported targets graphic and replaces the target support FAQ.
We've also taken the liberty to sort out the FAQ section on the udev rules for Linux.

Feature: Supported targets table

---

_pinouts/xilinx-14/data.py
_pinouts/xilinx-14/pinout_diagram.py
_pinouts/xilinx-14/styles.css
knowledge/pinouts.md

This PR adds the pinout for the Xilinx 14-pin JTAG connector that is found on all of their dev boards, this is especially useful for boards with their SoC, MPSoC, and RFSoC devices as the embedded ARM cores are on the same scan-chain and thus hooked up to the same connector.

Feature: Xilinx 14pin

---

getting-started.md
index.md

This PR fixes the lack of table of contents entry for the new MM32 targets guide.
Fixes #38

Fix: Missing MM32 ToC entry

---

getting-started.md
knowledge/compiling-windows.md

With thanks to @amyspark for giving the new Windows guide a read over and pointing out some mistakes we'd made, this PR fixes some spelling, wording and funky grammar in the guide as a follow-up to #40

Fix: Windows build typos

---

usage/stm32cubeide.md

Removed one too many backtick in #46 .
This causes a display error.
Fixed:

usage/stm32cubeide: Add missing backtick

---

knowledge/compiling-windows.md
usage/swo.md

In this PR we fix errors in the Compiling on Windows and SWO guides with thanks to Discord users 
lodwad and bivin.mato for pointing these issues out.
In the Compiling on Windows guide, the wrong package was named for the tool `pacboy`.
In the SWO usage guide, various links such as to the project's driver helper tree were stale and the instructions out of date against the current `main` firmware. The guide has been overhauled for spelling, grammar and punctuation in addition to the updates to correct the stale links and for the firmware.
We probably need a version of the SWO guide for v1.10 and previous, and the subject of how to go about documenting multiple firmware versions talked about. We feel that is not the place for this PR and that it needs some discussion.

Fix: Guide errors

---

supported-targets.md

In this PR we address the state of the targets list, making some minor corrections from the v1.10 version and updating it for all the new supported architectures and targets in what will be v2.0.
This introduces a support list for RISC-V targets and a proper one for Cortex-A targets.
We will introduce a list for Cortex-R targets when one gets supported for more than debugging.

Feature: Updated suported targets list

---

README.md
knowledge/compiling-windows.md

- The pacboy package is available in the pactoys package
- A bare-bones Docker image with Python3 may need to install python3-tk

Update Windows build instructions

---

knowledge/faq.md

The Amphenol connectors previously mentioned do not fit the cables as their shroud is too confining.

Update JTAG/SWD connector recommendations.

---

upgrade.md

Since the new bmputil v1 now supports automatic firmware updates we should promote that as the best way to keep the Black Magic Probe current.

upgrade: Update the documentation to promote bmputil v1 use.
